package ryan.cloud.myaccount.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ryan.cloud.myaccount.dao.model.Myusers;
import ryan.cloud.myaccount.dao.model.MyusersExample;

public interface MyusersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    long countByExample(MyusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    int deleteByExample(MyusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    int insert(Myusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    int insertSelective(Myusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    List<Myusers> selectByExample(MyusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    Myusers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    int updateByExampleSelective(@Param("record") Myusers record, @Param("example") MyusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    int updateByExample(@Param("record") Myusers record, @Param("example") MyusersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    int updateByPrimaryKeySelective(Myusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbg.generated Wed Jun 26 11:33:03 CST 2024
     */
    int updateByPrimaryKey(Myusers record);
}