package ryan.cloud.myapp.dao.module;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Sat Jun 22 16:34:07 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodName
     *
     * @mbg.generated Sat Jun 22 16:34:07 CST 2024
     */
    private String goodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remain
     *
     * @mbg.generated Sat Jun 22 16:34:07 CST 2024
     */
    private Integer remain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Sat Jun 22 16:34:07 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Sat Jun 22 16:34:07 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodName
     *
     * @return the value of goods.goodName
     *
     * @mbg.generated Sat Jun 22 16:34:07 CST 2024
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodName
     *
     * @param goodname the value for goods.goodName
     *
     * @mbg.generated Sat Jun 22 16:34:07 CST 2024
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname == null ? null : goodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remain
     *
     * @return the value of goods.remain
     *
     * @mbg.generated Sat Jun 22 16:34:07 CST 2024
     */
    public Integer getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remain
     *
     * @param remain the value for goods.remain
     *
     * @mbg.generated Sat Jun 22 16:34:07 CST 2024
     */
    public void setRemain(Integer remain) {
        this.remain = remain;
    }
}