package ryan.cloud.myaccout.dao.model;

public class Myusers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myusers.id
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myusers.username
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myusers.password
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myusers.role
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myusers.id
     *
     * @return the value of myusers.id
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myusers.id
     *
     * @param id the value for myusers.id
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myusers.username
     *
     * @return the value of myusers.username
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myusers.username
     *
     * @param username the value for myusers.username
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myusers.password
     *
     * @return the value of myusers.password
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myusers.password
     *
     * @param password the value for myusers.password
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myusers.role
     *
     * @return the value of myusers.role
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myusers.role
     *
     * @param role the value for myusers.role
     *
     * @mbg.generated Tue Jun 25 17:19:38 CST 2024
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}